### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by elklaaso** [django-fluent/django-fluent-blogs#16]
Hi,

I cannot install django fluent blogs in Django 1.8 / Python 3.

Is this because django categories does not support python 3?:

https://github.com/callowayproject/django-categories/issues/102

regards

**Comment by vdboor** [comment]
Well, the package itself hasn't been ported to Python 3 either. The other packages are, simply because the demand for it was much higher.

This package isn't strictly linked to django-categories. You can define `FLUENT_BLOGS_CATEGORY_MODEL` in your settings to have the models link to another package instead. In fact, I'm working on a django-categories-i18n package that provides translatable category names (plus that I'm annoyed by the speed of development in django-categories).

**Comment by vdboor** [comment]
the current version works on Python 3 for some time now. Closing.
